import {
  Home,
  Clapperboard,
  Tv,
  Sparkles,
  Flame,
  BookOpen,
  Layers,
  Book,
  FileText,
  Gamepad2,
  Bookmark,
  Heart,
  Calendar,
  History,
  ShieldCheck,
  Server,
  Cable,
  Settings,
  User,
  Search,
  Play,
  CheckCircle,
  Clock,
  Compass,
  TrendingUp,
  Award,
  Users,
  Moon,
  Sun,
  LogOut,
  LogIn,
  ChevronRight,
  ChevronDown,
  X,
  SlidersHorizontal,
  Plus,
  Trash2,
  Edit,
  ExternalLink,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  RefreshCw,
  Info,
  AlertTriangle,
  Radio,
  Share2,
  Target,
} from 'lucide-react';

export const APP_ICONS = {
  // Navigation & Categories
  home: Home,
  movies: Clapperboard,
  series: Tv,
  doramas: Sparkles,
  anime: Flame,
  manga: BookOpen,
  comics: Layers,
  books: Book,
  novels: FileText,
  games: Gamepad2,

  // Collections & Personal
  library: Bookmark,
  favorites: Heart,
  diary: Calendar,
  history: History,
  vault: ShieldCheck,
  personalMedia: Server,

  // Exploration
  discover: Compass,
  radar: Radio,
  guide: Calendar,
  releases: TrendingUp,
  community: Users,
  duo: Share2,

  // Journey
  insights: Award,
  goals: Target,
  wrapped: Sparkles,
  connections: Users,

  // System & Settings
  sources: Server,
  providers: Cable,
  settings: Settings,
  profile: User,

  // Actions & Controls
  search: Search,
  play: Play,
  check: CheckCircle,
  clock: Clock,
  themeDark: Moon,
  themeLight: Sun,
  logout: LogOut,
  login: LogIn,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  close: X,
  filter: SlidersHorizontal,
  add: Plus,
  delete: Trash2,
  edit: Edit,
  externalLink: ExternalLink,
  volume: Volume2,
  mute: VolumeX,
  fullscreen: Maximize,
  exitFullscreen: Minimize,
  refresh: RefreshCw,
  info: Info,
  alert: AlertTriangle,
} as const;
